---
# tasks file for docker-registry
- name: Login to DockerHub
  docker_login:
    username: utichawa
    password: yassine1996
    email: mechicheyassine@gmail.com
- name: Push to DockerHub
  command: docker push devops:latest
