---
# tasks file for docker-registry
- name: Login to DockerHub
  docker_login:
    username: utichawa
    password: yassine1996
    email: mechicheyassine@gmail.com
- name: Push to DockerHub
  docker_image:
    name: devops
    repository: utichawa/devops:latest
    push: yes
    source: local
